### PR TITLE
Resubmit issue 207

### PR DESCRIPTION
**Pull request by dbrnz**
This fixes the issue with unit tests.

### CODE REVIEW

**Comment by bw2** [comment]
Getting there. Still a couple failing 
https://travis-ci.org/github/bw2/ConfigArgParse/jobs/759397201

**Comment by dbrnz** [comment]
Hmm, everything tests OK for me run manually and I won't be able to dive deeper for a day or two now...

**Comment by dbrnz** [comment]
All now good!

**Comment by bw2** [comment]
Nice

**Pull request merged**
